version: "3.8"

services:
  web:
    build: 
      context: ./frontend
    ports:
      - "8000:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:5555
    networks:
      - myapp-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - myapp-network

  api:
    build: 
      context: ./backend
    ports:
      - "5555:5555"
    depends_on:
      - mongo
    environment:
      mongoDBURL : mongodb://mongo:27017/mydatabase
    volumes:
      - mongodb_data:/data/db
    networks:
      - myapp-network

volumes:
  mongodb_data:

networks:
  myapp-network:
    driver: bridge